apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - mongo-data-persistentvolumeclaim.yaml
