apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mongo
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: mongo
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mongo-data
